name: Codecoverage

on:
  push:
    branches:
      - main

jobs:
  codecoverage:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git user
        run: |
          git config --global user.name "farmacodeunipd"
          git config --global user.email "farmacode.swe.unipd@gmail.com"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Run tests and stop if they do not pass
        run: |
          ci_env=$(bash <(curl -s https://codecov.io/env))
          docker exec $ci_env mvp_python-api_1 pytest tests/test_algo.py --cov=. --cov-report=xml:/tests/coverage.xml --verbose
          docker exec $ci_env mvp_react-app_1 npm test
          docker exec $ci_env mvp_express_1 npm test
        continue-on-error: false

      - name: Copy coverage reports
        run: |
          docker cp mvp_python-api_1:/tests/coverage.xml ./coverage-python-api.xml
          docker cp mvp_react-app_1:/client/coverage/coverage-final.json ./coverage-react.json
          docker cp mvp_express_1:/express/coverage/coverage-final.json ./coverage-express.json

      - name: Stop and remove Docker containers
        run: docker-compose down

      - name: Upload Python API coverage report to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage-python-api.xml
          flags: python-api
          name: codecov-python-api

      - name: Upload React application coverage report to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage-react.json
          flags: react-app
          name: codecov-react-app

      - name: Upload Express coverage report to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage-express.json
          flags: express
          name: codecov-express